// Generated by Supabase CLI / MCP — do not hand-edit.
// Regenerate with: `supabase gen types typescript --project-id yefoofucailpzrasmzeh`
// or via the Supabase MCP `generate_typescript_types`.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      briefing_subscriptions: {
        Row: {
          active: boolean
          audience: Database["public"]["Enums"]["briefing_audience"]
          cadence: Database["public"]["Enums"]["briefing_cadence"]
          channel: Database["public"]["Enums"]["delivery_channel"]
          created_at: string
          id: string
          topic: string | null
          user_id: string
        }
        Insert: {
          active?: boolean
          audience: Database["public"]["Enums"]["briefing_audience"]
          cadence: Database["public"]["Enums"]["briefing_cadence"]
          channel: Database["public"]["Enums"]["delivery_channel"]
          created_at?: string
          id?: string
          topic?: string | null
          user_id: string
        }
        Update: {
          active?: boolean
          audience?: Database["public"]["Enums"]["briefing_audience"]
          cadence?: Database["public"]["Enums"]["briefing_cadence"]
          channel?: Database["public"]["Enums"]["delivery_channel"]
          created_at?: string
          id?: string
          topic?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "briefing_subscriptions_topic_fkey"
            columns: ["topic"]
            isOneToOne: false
            referencedRelation: "taxonomy_topics"
            referencedColumns: ["slug"]
          }
        ]
      }
      briefings: {
        Row: {
          audience: Database["public"]["Enums"]["briefing_audience"]
          cadence: Database["public"]["Enums"]["briefing_cadence"]
          conscience_concerns: string[]
          conscience_notes: string | null
          conscience_verdict: Database["public"]["Enums"]["conscience_verdict"]
          created_at: string
          headline: string
          id: string
          lens_findings: Json
          published_at: string | null
          run_id: string | null
          sections: Json
          summary: string
          topic: string | null
          trend_ids: string[]
          version: number
          window_end: string
          window_start: string
        }
        Insert: {
          audience: Database["public"]["Enums"]["briefing_audience"]
          cadence: Database["public"]["Enums"]["briefing_cadence"]
          conscience_concerns?: string[]
          conscience_notes?: string | null
          conscience_verdict?: Database["public"]["Enums"]["conscience_verdict"]
          created_at?: string
          headline: string
          id?: string
          lens_findings?: Json
          published_at?: string | null
          run_id?: string | null
          sections?: Json
          summary: string
          topic?: string | null
          trend_ids?: string[]
          version?: number
          window_end: string
          window_start: string
        }
        Update: {
          audience?: Database["public"]["Enums"]["briefing_audience"]
          cadence?: Database["public"]["Enums"]["briefing_cadence"]
          conscience_concerns?: string[]
          conscience_notes?: string | null
          conscience_verdict?: Database["public"]["Enums"]["conscience_verdict"]
          created_at?: string
          headline?: string
          id?: string
          lens_findings?: Json
          published_at?: string | null
          run_id?: string | null
          sections?: Json
          summary?: string
          topic?: string | null
          trend_ids?: string[]
          version?: number
          window_end?: string
          window_start?: string
        }
        Relationships: [
          {
            foreignKeyName: "briefings_run_id_fkey"
            columns: ["run_id"]
            isOneToOne: false
            referencedRelation: "runs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "briefings_topic_fkey"
            columns: ["topic"]
            isOneToOne: false
            referencedRelation: "taxonomy_topics"
            referencedColumns: ["slug"]
          }
        ]
      }
      documents: {
        Row: {
          author: string | null
          embedding: string | null
          external_id: string
          fetched_at: string
          fts: unknown
          id: string
          lang: string
          published_at: string | null
          raw_payload: Json | null
          source_id: string
          text: string
          title: string | null
          url: string | null
        }
        Insert: {
          author?: string | null
          embedding?: string | null
          external_id: string
          fetched_at?: string
          fts?: unknown
          id?: string
          lang?: string
          published_at?: string | null
          raw_payload?: Json | null
          source_id: string
          text: string
          title?: string | null
          url?: string | null
        }
        Update: {
          author?: string | null
          embedding?: string | null
          external_id?: string
          fetched_at?: string
          fts?: unknown
          id?: string
          lang?: string
          published_at?: string | null
          raw_payload?: Json | null
          source_id?: string
          text?: string
          title?: string | null
          url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "documents_source_id_fkey"
            columns: ["source_id"]
            isOneToOne: false
            referencedRelation: "sources"
            referencedColumns: ["id"]
          }
        ]
      }
      enrichments: {
        Row: {
          detected_lang: string | null
          document_id: string
          embedding_dim: number | null
          emotion: Json | null
          enriched_at: string
          entities: Json
          sentiment_conf: number | null
          sentiment_label: Database["public"]["Enums"]["sentiment_label"] | null
          sentiment_score: number | null
          stance: Json | null
          text_en: string | null
          topics: string[]
        }
        Insert: {
          detected_lang?: string | null
          document_id: string
          embedding_dim?: number | null
          emotion?: Json | null
          enriched_at?: string
          entities?: Json
          sentiment_conf?: number | null
          sentiment_label?:
            | Database["public"]["Enums"]["sentiment_label"]
            | null
          sentiment_score?: number | null
          stance?: Json | null
          text_en?: string | null
          topics?: string[]
        }
        Update: {
          detected_lang?: string | null
          document_id?: string
          embedding_dim?: number | null
          emotion?: Json | null
          enriched_at?: string
          entities?: Json
          sentiment_conf?: number | null
          sentiment_label?:
            | Database["public"]["Enums"]["sentiment_label"]
            | null
          sentiment_score?: number | null
          stance?: Json | null
          text_en?: string | null
          topics?: string[]
        }
        Relationships: [
          {
            foreignKeyName: "enrichments_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: true
            referencedRelation: "documents"
            referencedColumns: ["id"]
          }
        ]
      }
      runs: {
        Row: {
          error: string | null
          finished_at: string | null
          id: string
          input: Json | null
          kind: Database["public"]["Enums"]["run_kind"]
          lens_findings: Json | null
          output: Json | null
          started_at: string
          status: Database["public"]["Enums"]["run_status"]
        }
        Insert: {
          error?: string | null
          finished_at?: string | null
          id?: string
          input?: Json | null
          kind: Database["public"]["Enums"]["run_kind"]
          lens_findings?: Json | null
          output?: Json | null
          started_at?: string
          status?: Database["public"]["Enums"]["run_status"]
        }
        Update: {
          error?: string | null
          finished_at?: string | null
          id?: string
          input?: Json | null
          kind?: Database["public"]["Enums"]["run_kind"]
          lens_findings?: Json | null
          output?: Json | null
          started_at?: string
          status?: Database["public"]["Enums"]["run_status"]
        }
        Relationships: []
      }
      sources: {
        Row: {
          active: boolean
          created_at: string
          endpoint: string
          id: string
          kind: Database["public"]["Enums"]["source_kind"]
          label: string
          lang: string | null
          last_polled_at: string | null
          poll_seconds: number | null
          topics: string[]
        }
        Insert: {
          active?: boolean
          created_at?: string
          endpoint: string
          id?: string
          kind: Database["public"]["Enums"]["source_kind"]
          label: string
          lang?: string | null
          last_polled_at?: string | null
          poll_seconds?: number | null
          topics?: string[]
        }
        Update: {
          active?: boolean
          created_at?: string
          endpoint?: string
          id?: string
          kind?: Database["public"]["Enums"]["source_kind"]
          label?: string
          lang?: string | null
          last_polled_at?: string | null
          poll_seconds?: number | null
          topics?: string[]
        }
        Relationships: []
      }
      taxonomy_topics: {
        Row: {
          active: boolean
          created_at: string
          description: string | null
          label: string
          parent_slug: string | null
          slug: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          description?: string | null
          label: string
          parent_slug?: string | null
          slug: string
        }
        Update: {
          active?: boolean
          created_at?: string
          description?: string | null
          label?: string
          parent_slug?: string | null
          slug?: string
        }
        Relationships: [
          {
            foreignKeyName: "taxonomy_topics_parent_slug_fkey"
            columns: ["parent_slug"]
            isOneToOne: false
            referencedRelation: "taxonomy_topics"
            referencedColumns: ["slug"]
          }
        ]
      }
      trends: {
        Row: {
          detected_at: string
          document_ids: string[]
          id: string
          kind: Database["public"]["Enums"]["trend_kind"]
          magnitude: number
          scope: Json
          summary: string
          window_end: string
          window_start: string
        }
        Insert: {
          detected_at?: string
          document_ids?: string[]
          id?: string
          kind: Database["public"]["Enums"]["trend_kind"]
          magnitude: number
          scope: Json
          summary: string
          window_end: string
          window_start: string
        }
        Update: {
          detected_at?: string
          document_ids?: string[]
          id?: string
          kind?: Database["public"]["Enums"]["trend_kind"]
          magnitude?: number
          scope?: Json
          summary?: string
          window_end?: string
          window_start?: string
        }
        Relationships: []
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      hybrid_search: {
        Args: {
          match_count?: number
          published_after?: string
          published_before?: string
          q_embedding?: string
          q_text?: string
          source_ids?: string[]
          topic_filter?: string[]
        }
        Returns: {
          bm25_score: number
          fused_score: number
          id: string
          lang: string
          published_at: string
          source_id: string
          text: string
          title: string
          url: string
          vector_score: number
        }[]
      }
      show_limit: { Args: never; Returns: number }
      show_trgm: { Args: { "": string }; Returns: string[] }
    }
    Enums: {
      briefing_audience: "campaigner" | "leadership"
      briefing_cadence: "daily" | "weekly" | "ad_hoc"
      conscience_verdict: "approved" | "revise" | "block"
      delivery_channel: "email" | "slack" | "in_app"
      run_kind: "briefing" | "query" | "trend_detect"
      run_status: "pending" | "running" | "completed" | "failed"
      sentiment_label: "positive" | "negative" | "neutral" | "mixed"
      source_kind:
        | "rss"
        | "gdelt"
        | "newsapi"
        | "bluesky"
        | "mastodon"
        | "reddit"
      trend_kind:
        | "volume_spike"
        | "sentiment_shift"
        | "narrative_emergence"
        | "entity_cooccurrence"
    }
    CompositeTypes: { [_ in never]: never }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  T extends keyof DefaultSchema["Tables"]
> = DefaultSchema["Tables"][T]["Row"]

export type TablesInsert<
  T extends keyof DefaultSchema["Tables"]
> = DefaultSchema["Tables"][T]["Insert"]

export type TablesUpdate<
  T extends keyof DefaultSchema["Tables"]
> = DefaultSchema["Tables"][T]["Update"]

export type Enums<T extends keyof DefaultSchema["Enums"]> = DefaultSchema["Enums"][T]
